import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
]

[font]
size = 14
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#normal = { family = "Recursive Mono Casual Static", style = "Medium" }
normal = { family = "FiraCode Nerd Font", style = "Retina" }
